config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
  path('', views.index, name='index'),
  path('<int:question_id>/', views.detail, name='detail'),
  path('answer/create/<int:question_id>/', views.answer_create, name='answer_create'),
  path('question/create/', views.question_create, name='question_create'),
  path('answer/favorite/<int:answer_id>/', views.answer_favorite, name='answer_favorite'),

]

polls/models.py
from django.db import models

class Question(models.Model):
  subject = models.CharField(max_length=200)
  content = models.TextField()
  pub_date = models.DateTimeField()

class Answer(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  content = models.TextField()
  create_date = models.DateTimeField()

# polls_favorite
class Favorite(models.Model):
  Answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
  #                    (255.255.255.255)
  ip = models.CharField(max_length = 15)
  create_date = models.DateTimeField() 

polls/forms.py
from django import forms
from .models import Question

class QuestionForm(forms.ModelForm):
  class Meta:
    model = Question
    fields = ['subject', 'content']
    # template에서 직접 디자인하기 위해 widgets 항목 제거
    # widgets = {
    #   'subject': forms.TextInput(attrs={'class': 'form-control'}),
    #   'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
    # }
    labels = {
      'subject': '제목',
      'content': '내용',
    }

from .models import Answer
class AnswerForm(forms.ModelForm):
  class Meta:
    model = Answer
    fields = ['content']
    labels = {
      'content': '답변내용',
    }

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Favorite, Question , Answer


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip
    
def answer_favorite(request, answer_id):
    print(answer_id) # 좋아요 대상 답변 번호
    # IP 주소 확인 코드
    ip = get_client_ip(request)
    print(ip)
    answer = Answer.objects.get(pk=answer_id)

    f = Favorite(ip=ip, create_date=timezone.now(), answer=answer)
    f.save()
    return redirect('/polls/')

def index(request):
  # question_list = Question.objects.order_by('-pub_date')
  # result = [ q.subject for q in question_list ]
  # return HttpResponse( str(result) )

  question_list = Question.objects.order_by('-pub_date')

  context = {
    'question_list': question_list
  }
  return render(request, 'polls/question_list.html', context)

from django.shortcuts import get_object_or_404

def detail(request, question_id):
  question = get_object_or_404(Question, id=question_id)
  context = {
    'question': question
  }
  return render(request, 'polls/question_detail.html', context)

from django.utils import timezone
# from .models import Answer
from django.shortcuts import redirect


# def answer_create(request, question_id):
#   question = get_object_or_404(Question, pk=question_id)
#   question.answer_set.create(
#     content=request.POST.get('content'), create_date=timezone.now())
  
#   # answer = Answer(
#   #   question=question, content=request.POST.get('content'),
#   #   create_date=timezone.now())
#   # answer.save()
  
#   return redirect('polls:detail', question_id=question.id)

from .forms import AnswerForm

def answer_create(request, question_id):
  question = get_object_or_404(Question, pk=question_id)
  
  if request.method == "POST":
    form = AnswerForm(request.POST)
    if form.is_valid():
      answer = form.save(commit=False)
      answer.create_date = timezone.now()
      answer.question = question
      answer.save()
      return redirect('polls:detail', question_id=question.id)
  else:
    form = AnswerForm()

  context = {'question': question, 'form': form}

  return render(request, 'polls/question_detail.html', context)

from .forms import QuestionForm

def question_create(request):
  if request.method == 'POST':
    form = QuestionForm(request.POST)
    if form.is_valid():
      question = form.save(commit=False)
      question.pub_date = timezone.now()
      question.save()
      return redirect('polls:index')
  else:
    form = QuestionForm()

  context = {'form': form}

  return render(request, 'polls/question_form.html', context)

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

  <title>Hello, MySite!</title>
</head>

<body>
  <!-- 네비게이션바 -->
  {% include 'navbar.html' %}

  <!-- 기본 템플릿 안에 삽입될 내용 Start -->
  {% block content %}
  {% endblock %}
  <!-- 기본 템플릿 안에 삽입될 내용 End -->
</body>

</html>

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'polls:index' %}">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">로그인</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

templates/polls/question_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <h2 class="border-bottom py-2">{{ question.subject }}</h2>
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">
        {{ question.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{ question.pub_date }}
        </div>
      </div>
    </div>
  </div>
  <h5 class="border-bottom my-3 py-2">
    {{question.answer_set.count}}개의 답변이 있습니다.
  </h5>
  {% for answer in question.answer_set.all %}
  <div class="card my-3">
    <div class="card-body">
      <div class="card-text" style="white-space: pre-line;">
        {{ answer.content }}
      </div>
      <div class="d-flex justify-content-end">
        <div class="badge badge-light p-2">
          {{ answer.create_date }}
        </div>
      </div>
    </div>
  </div>
  {% endfor %}
  <form action="{% url 'polls:answer_create' question.id %}" method="post" class="my-3">
    {% csrf_token %}
    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->
    <div class="form-group">
      <textarea name="content" id="content" class="form-control" rows="10"></textarea>
    </div>
    <input type="submit" value="답변등록" class="btn btn-primary">
  </form>
</div>
{% endblock %}

templates/polls/question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <h5 class="my-3 border-bottom pb-2">질문등록</h5>
  <form method="post" class="post-form my-3">
    {% csrf_token %}

    <!-- 오류표시 Start -->
    {% if form.errors %}
    <div class="alert alert-danger" role="alert">
      {% for field in form %}
        {% if field.errors %}
          <strong>{{ field.label }}</strong>
          {{ field.errors }}
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}
    <!-- 오류표시 End -->

    <div class="form-group">
      <label for="subject">제목</label>
      <input type="text" class="form-control" name="subject" value="{{ form.subject.value|default_if_none:'' }}">
    </div>
    <div class="form-group">
      <label for="content">내용</label>
      <textarea class="form-control" name="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
    </div>

    <button type="submit" class="btn btn-primary">저장하기</button>
  </form>
</div>
{% endblock %}

templates/polls/question_list.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
  <table class="table">
    <thead>
      <tr class="table-dark">
        <th>번호</th>
        <th>제목</th>
        <th>작성일시</th>
      </tr>
    </thead>
    <tbody>
      {% if question_list %}
        {% for question in question_list %}
        <tr>
          <td>{{ forloop.counter }}</td>
          <td>
            <a href="{% url 'polls:detail' question.id %}">{{ question.subject }}</a>
            <span class="badge bg-warning text-dark">{{ question.answer_set.count }}</span>           
          </td>
          <td>{{ question.pub_date }}</td>
        </tr>
        {% endfor %}
      {% else %}
        <tr>
          <td colspan="3">질문이 없습니다.</td>
        </tr>
      {% endif %}
    </tbody>
  </table>

  <a href="{% url 'polls:question_create' %}" class="btn btn-primary">
    질문 등록하기
  </a>

</div>
{% endblock %}